
package net.ddraig.justasphalt.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.ddraig.justasphalt.block.YellowAsphaltStairsBlock;
import net.ddraig.justasphalt.block.YellowAsphaltSlabBlock;
import net.ddraig.justasphalt.block.YellowAsphaltBlock;
import net.ddraig.justasphalt.block.WhiteAsphaltStairsBlock;
import net.ddraig.justasphalt.block.WhiteAsphaltSlabBlock;
import net.ddraig.justasphalt.block.WhiteAsphaltBlock;
import net.ddraig.justasphalt.block.RedAsphaltStairsBlock;
import net.ddraig.justasphalt.block.RedAsphaltSlabBlock;
import net.ddraig.justasphalt.block.RedAsphaltBlock;
import net.ddraig.justasphalt.block.PurpleAsphaltStairsBlock;
import net.ddraig.justasphalt.block.PurpleAsphaltSlabBlock;
import net.ddraig.justasphalt.block.PurpleAsphaltBlock;
import net.ddraig.justasphalt.block.PinkAsphaltStairsBlock;
import net.ddraig.justasphalt.block.PinkAsphaltSlabBlock;
import net.ddraig.justasphalt.block.PinkAsphaltBlock;
import net.ddraig.justasphalt.block.OrangeAsphaltStairsBlock;
import net.ddraig.justasphalt.block.OrangeAsphaltSlabBlock;
import net.ddraig.justasphalt.block.OrangeAsphaltBlock;
import net.ddraig.justasphalt.block.MagentaAsphaltStairsBlock;
import net.ddraig.justasphalt.block.MagentaAsphaltSlabBlock;
import net.ddraig.justasphalt.block.MagentaAsphaltBlock;
import net.ddraig.justasphalt.block.LimeAsphaltStairsBlock;
import net.ddraig.justasphalt.block.LimeAsphaltSlabBlock;
import net.ddraig.justasphalt.block.LimeAsphaltBlock;
import net.ddraig.justasphalt.block.LightGrayAsphaltStairsBlock;
import net.ddraig.justasphalt.block.LightGrayAsphaltSlabBlock;
import net.ddraig.justasphalt.block.LightGrayAsphaltBlock;
import net.ddraig.justasphalt.block.LightBlueAsphaltStairsBlock;
import net.ddraig.justasphalt.block.LightBlueAsphaltSlabBlock;
import net.ddraig.justasphalt.block.LightBlueAsphaltBlock;
import net.ddraig.justasphalt.block.GreenAsphaltStairsBlock;
import net.ddraig.justasphalt.block.GreenAsphaltSlabBlock;
import net.ddraig.justasphalt.block.GreenAsphaltBlock;
import net.ddraig.justasphalt.block.GrayAsphaltStairsBlock;
import net.ddraig.justasphalt.block.GrayAsphaltSlabBlock;
import net.ddraig.justasphalt.block.GrayAsphaltBlock;
import net.ddraig.justasphalt.block.CyanAsphaltStairsBlock;
import net.ddraig.justasphalt.block.CyanAsphaltSlabBlock;
import net.ddraig.justasphalt.block.CyanAsphaltBlock;
import net.ddraig.justasphalt.block.BrownAsphaltStairsBlock;
import net.ddraig.justasphalt.block.BrownAsphaltSlabBlock;
import net.ddraig.justasphalt.block.BrownAsphaltBlock;
import net.ddraig.justasphalt.block.BlueAsphaltStairsBlock;
import net.ddraig.justasphalt.block.BlueAsphaltSlabBlock;
import net.ddraig.justasphalt.block.BlueAsphaltBlock;
import net.ddraig.justasphalt.block.BlackAsphaltStairsBlock;
import net.ddraig.justasphalt.block.BlackAsphaltSlabBlock;
import net.ddraig.justasphalt.block.BlackAsphaltBlock;
import net.ddraig.justasphalt.block.AsphaltStairsBlock;
import net.ddraig.justasphalt.block.AsphaltSlabBlock;
import net.ddraig.justasphalt.block.AsphaltBlock;
import net.ddraig.justasphalt.JustAsphaltMod;

public class JustAsphaltModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, JustAsphaltMod.MODID);
	public static final RegistryObject<Block> ASPHALT = REGISTRY.register("asphalt", () -> new AsphaltBlock());
	public static final RegistryObject<Block> BLACK_ASPHALT = REGISTRY.register("black_asphalt", () -> new BlackAsphaltBlock());
	public static final RegistryObject<Block> BLUE_ASPHALT = REGISTRY.register("blue_asphalt", () -> new BlueAsphaltBlock());
	public static final RegistryObject<Block> BROWN_ASPHALT = REGISTRY.register("brown_asphalt", () -> new BrownAsphaltBlock());
	public static final RegistryObject<Block> CYAN_ASPHALT = REGISTRY.register("cyan_asphalt", () -> new CyanAsphaltBlock());
	public static final RegistryObject<Block> GRAY_ASPHALT = REGISTRY.register("gray_asphalt", () -> new GrayAsphaltBlock());
	public static final RegistryObject<Block> GREEN_ASPHALT = REGISTRY.register("green_asphalt", () -> new GreenAsphaltBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_ASPHALT = REGISTRY.register("light_blue_asphalt", () -> new LightBlueAsphaltBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_ASPHALT = REGISTRY.register("light_gray_asphalt", () -> new LightGrayAsphaltBlock());
	public static final RegistryObject<Block> LIME_ASPHALT = REGISTRY.register("lime_asphalt", () -> new LimeAsphaltBlock());
	public static final RegistryObject<Block> MAGENTA_ASPHALT = REGISTRY.register("magenta_asphalt", () -> new MagentaAsphaltBlock());
	public static final RegistryObject<Block> ORANGE_ASPHALT = REGISTRY.register("orange_asphalt", () -> new OrangeAsphaltBlock());
	public static final RegistryObject<Block> PINK_ASPHALT = REGISTRY.register("pink_asphalt", () -> new PinkAsphaltBlock());
	public static final RegistryObject<Block> PURPLE_ASPHALT = REGISTRY.register("purple_asphalt", () -> new PurpleAsphaltBlock());
	public static final RegistryObject<Block> RED_ASPHALT = REGISTRY.register("red_asphalt", () -> new RedAsphaltBlock());
	public static final RegistryObject<Block> WHITE_ASPHALT = REGISTRY.register("white_asphalt", () -> new WhiteAsphaltBlock());
	public static final RegistryObject<Block> YELLOW_ASPHALT = REGISTRY.register("yellow_asphalt", () -> new YellowAsphaltBlock());
	public static final RegistryObject<Block> ASPHALT_SLAB = REGISTRY.register("asphalt_slab", () -> new AsphaltSlabBlock());
	public static final RegistryObject<Block> BLACK_ASPHALT_SLAB = REGISTRY.register("black_asphalt_slab", () -> new BlackAsphaltSlabBlock());
	public static final RegistryObject<Block> BLUE_ASPHALT_SLAB = REGISTRY.register("blue_asphalt_slab", () -> new BlueAsphaltSlabBlock());
	public static final RegistryObject<Block> BROWN_ASPHALT_SLAB = REGISTRY.register("brown_asphalt_slab", () -> new BrownAsphaltSlabBlock());
	public static final RegistryObject<Block> CYAN_ASPHALT_SLAB = REGISTRY.register("cyan_asphalt_slab", () -> new CyanAsphaltSlabBlock());
	public static final RegistryObject<Block> GRAY_ASPHALT_SLAB = REGISTRY.register("gray_asphalt_slab", () -> new GrayAsphaltSlabBlock());
	public static final RegistryObject<Block> GREEN_ASPHALT_SLAB = REGISTRY.register("green_asphalt_slab", () -> new GreenAsphaltSlabBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_ASPHALT_SLAB = REGISTRY.register("light_blue_asphalt_slab", () -> new LightBlueAsphaltSlabBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_ASPHALT_SLAB = REGISTRY.register("light_gray_asphalt_slab", () -> new LightGrayAsphaltSlabBlock());
	public static final RegistryObject<Block> LIME_ASPHALT_SLAB = REGISTRY.register("lime_asphalt_slab", () -> new LimeAsphaltSlabBlock());
	public static final RegistryObject<Block> MAGENTA_ASPHALT_SLAB = REGISTRY.register("magenta_asphalt_slab", () -> new MagentaAsphaltSlabBlock());
	public static final RegistryObject<Block> ORANGE_ASPHALT_SLAB = REGISTRY.register("orange_asphalt_slab", () -> new OrangeAsphaltSlabBlock());
	public static final RegistryObject<Block> PINK_ASPHALT_SLAB = REGISTRY.register("pink_asphalt_slab", () -> new PinkAsphaltSlabBlock());
	public static final RegistryObject<Block> PURPLE_ASPHALT_SLAB = REGISTRY.register("purple_asphalt_slab", () -> new PurpleAsphaltSlabBlock());
	public static final RegistryObject<Block> RED_ASPHALT_SLAB = REGISTRY.register("red_asphalt_slab", () -> new RedAsphaltSlabBlock());
	public static final RegistryObject<Block> WHITE_ASPHALT_SLAB = REGISTRY.register("white_asphalt_slab", () -> new WhiteAsphaltSlabBlock());
	public static final RegistryObject<Block> YELLOW_ASPHALT_SLAB = REGISTRY.register("yellow_asphalt_slab", () -> new YellowAsphaltSlabBlock());
	public static final RegistryObject<Block> ASPHALT_STAIRS = REGISTRY.register("asphalt_stairs", () -> new AsphaltStairsBlock());
	public static final RegistryObject<Block> BLACK_ASPHALT_STAIRS = REGISTRY.register("black_asphalt_stairs", () -> new BlackAsphaltStairsBlock());
	public static final RegistryObject<Block> BLUE_ASPHALT_STAIRS = REGISTRY.register("blue_asphalt_stairs", () -> new BlueAsphaltStairsBlock());
	public static final RegistryObject<Block> BROWN_ASPHALT_STAIRS = REGISTRY.register("brown_asphalt_stairs", () -> new BrownAsphaltStairsBlock());
	public static final RegistryObject<Block> CYAN_ASPHALT_STAIRS = REGISTRY.register("cyan_asphalt_stairs", () -> new CyanAsphaltStairsBlock());
	public static final RegistryObject<Block> GRAY_ASPHALT_STAIRS = REGISTRY.register("gray_asphalt_stairs", () -> new GrayAsphaltStairsBlock());
	public static final RegistryObject<Block> GREEN_ASPHALT_STAIRS = REGISTRY.register("green_asphalt_stairs", () -> new GreenAsphaltStairsBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_ASPHALT_STAIRS = REGISTRY.register("light_blue_asphalt_stairs", () -> new LightBlueAsphaltStairsBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_ASPHALT_STAIRS = REGISTRY.register("light_gray_asphalt_stairs", () -> new LightGrayAsphaltStairsBlock());
	public static final RegistryObject<Block> LIME_ASPHALT_STAIRS = REGISTRY.register("lime_asphalt_stairs", () -> new LimeAsphaltStairsBlock());
	public static final RegistryObject<Block> MAGENTA_ASPHALT_STAIRS = REGISTRY.register("magenta_asphalt_stairs", () -> new MagentaAsphaltStairsBlock());
	public static final RegistryObject<Block> ORANGE_ASPHALT_STAIRS = REGISTRY.register("orange_asphalt_stairs", () -> new OrangeAsphaltStairsBlock());
	public static final RegistryObject<Block> PINK_ASPHALT_STAIRS = REGISTRY.register("pink_asphalt_stairs", () -> new PinkAsphaltStairsBlock());
	public static final RegistryObject<Block> PURPLE_ASPHALT_STAIRS = REGISTRY.register("purple_asphalt_stairs", () -> new PurpleAsphaltStairsBlock());
	public static final RegistryObject<Block> RED_ASPHALT_STAIRS = REGISTRY.register("red_asphalt_stairs", () -> new RedAsphaltStairsBlock());
	public static final RegistryObject<Block> WHITE_ASPHALT_STAIRS = REGISTRY.register("white_asphalt_stairs", () -> new WhiteAsphaltStairsBlock());
	public static final RegistryObject<Block> YELLOW_ASPHALT_STAIRS = REGISTRY.register("yellow_asphalt_stairs", () -> new YellowAsphaltStairsBlock());
}
